import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from '@/lib/apollo-provider';
import Toast from '@/lib/Toast';

const inter = Inter({ subsets: ['latin'], display: 'swap', adjustFontFallback: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative flex min-h-screen items-center justify-center bg-[#070B15] text-gray-100`}
      >
        <ApolloWrapper>{children}</ApolloWrapper>
        <Toast />
      </body>
    </html>
  );
}
